### ISSUE TITLE
Sidebar height is off and not all text is visible in Firefox

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/image_space#10]
The instructions in the sidebar on the left are not entirely visible. When I scroll to the  bottom, I can't read the last line - seems the height of the div is off somehow.

I'm on Ubuntu 14.04 with Firefox 36.0.1.

It works fine in Chrome however...

**Comment by jeffbaumes** [comment]
This should be fixed on firefox now.

**Comment by wmburke** [comment]
While the effect is the same, I believe that you just added padding to the bottom of the sidebar div. The height is still off. I can tell because you can't see the bottom of the scroll bar. I don't think this is something that has to be fixed at this point, especially with the discussion of changing the UI, but I wanted to make certain the info was captured.
