### ISSUE TITLE
Correctly display image/svg+xml images

### ISSUE THREAD

**Issue by jeffbaumes** [memex-explorer/image_space#108]
Search for "bullet" to see the issue in the first few results. If the contentType is `image/svg+xml` then use this logic to embed the svg instead of creating an img tag:

https://css-tricks.com/svg-use-external-source/

I am fairly certain similarity will not work in this case so we may want to disable the similarity/background search for these.

**Comment by danlamanna** [comment]
Currently 828/1434459 of images are SVGs, and they pose a number of issues with properly embedding and sizing them from an outside source.
