### ISSUE TITLE
Ability to save relevant images

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/image_space#12]
I know this is not something previously discussed but as of now, I don't see a way to save images and find them again later. For the searches, you mention that you can bookmark the url in the browser, but I don't see where there is any permalink for an image.

Is this possible?

**Comment by jeffbaumes** [comment]
This is certainly possible. For now I've added a permalink button to the image details. This will link to a search with just that image and you can then copy that URL to keep track of that image.

In the future I want to store user saved searches and images in Girder. For now you need to track things with URLs.

**Comment by wmburke** [comment]
I think that's fine, Jeff. Thanks

On Mon, Mar 23, 2015 at 11:02 AM, Jeffrey Baumes notifications@github.com wrote:This is certainly possible. For now I've added a permalink button to the image details. This will link to a search with just that image and you can then copy that URL to keep track of that image.

In the future I want to store user saved searches and images in Girder. For now you need to track things with URLs.
