### ISSUE TITLE
Comparing image origins

### ISSUE THREAD

**Issue by danlamanna** [memex-explorer/image_space#123]
It should be easier to crosslink to FacetView if a user has several images they want to obtain more information about.

**Comment by jeffbaumes** [comment]
This would involve UI for selecting multiple images, then going to a separate "compare" page that has a comparison table. Since this is a somewhat major feature, I'm not putting in the SUG milestone for now.

**Comment by jeffbaumes** [comment]
This could also mean displaying aggregate properties on a selected set of images, not just comparisons.

**Comment by chrismattmann** [comment]
we fixed this in a combination of Nutch/Sparkler, Facetview and ImageSpace
