### ISSUE TITLE
At around 1350 px wide or less on Chrome, the login/register UI elements dissappear

### ISSUE THREAD

**Issue by jeffbaumes** [memex-explorer/image_space#134]

**Comment by wmburke** [comment]
This problem seems to be solved but at about 1000px on my Linux box in Firefox, the ImageSpace name disappears from the top menu bar.

**Comment by danlamanna** [comment]
I don't know that that's an issue, a lot of responsive apps do that to save space. Combined with the fact that the search bar is now always in the top bar, the home page doesn't give any additional functionality that isn't available everywhere else in the app.

**Comment by wmburke** [comment]
Fair point. Thanks. I'm fine with it for now.
