### ISSUE TITLE
Ability to open cached version of an ad

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/image_space#137]
@chrismattmann Please elaborate on this. I think it ties in with the recent changes to enable opening of facetview or the original ad, but I believe it also goes farther.

**Comment by danlamanna** [comment]
I see this as crucial to FacetView. I'm unsure if the crawling process scrapes css but it would be nice to have a perfect snapshot of what the ad looked like at the time of crawling without any external dependencies.

**Comment by chrismattmann** [comment]
we closed this and made it a part of Facetview so we're done!
