### ISSUE TITLE
Loading image data from a remote location

### ISSUE THREAD

**Issue by pmlandwehr** [memex-explorer/image_space#155]
It'd be cool to be able to load image data from a remote endpoint. (That is, to be able to set `IMAGE_SPACE_SOLR_PREFIX` to point at an http file and have Image Space load the image data from that target.)

**Comment by jeffbaumes** [comment]
Could you elaborate a bit more? What would the http target contain exactly? A directory of images? A file that is a listing of image URLs?

Currently the ingest is done though the separate [ImageCat](https://github.com/chrismattmann/imagecat) repository. The loading of new data in ImageSpace is limited to one by one user uploads, which are placed in a user space to drive searches into the full index but are currently not added to the full index themselves (that is, if you upload an image, then other people will still not find that image in subsequent searches - it is just in your user space).

**Comment by pmlandwehr** [comment]
After some additional messing around, it turns out I just had a few things misconfigured, & all is well. Please close this up.
