### ISSUE TITLE
Upper Casing FileNames in Search Results

### ISSUE THREAD

**Issue by harsham05** [memex-explorer/image_space#156]
@danlamanna 
May I please know why we are upper casing search results, which affects the HTTP file mount resulting in broken image links?

https://github.com/memex-explorer/image_space/blob/master/imagespace/server/imagesearch_rest.py#L128

I am guessing this is specific to weapons. This affects deployment to other domains.

FYI, I am using [parser-indexer](https://github.com/thammegowda/parser-indexer) Pipeline for Solr ingestion.

Thank you!

**Comment by danlamanna** [comment]
Yup, this is specific to weapons - [only recently](https://github.com/memex-explorer/image_space/pull/151) has ImageSpace started separating this sort of logic out into a weapons-specific plugin.

I'll separate this out in a PR later today, it should be trivial to do. There are certainly other areas that are weapons specific in the codebase that need to be decoupled; we are mostly dealing with these as they arise, so feel free to put in issues if/when you encounter other instances.

**Comment by harsham05** [comment]
Thanks @danlamanna !

**Comment by danlamanna** [comment]
Closed via #157
