### ISSUE TITLE
IQR work flow issues

### ISSUE THREAD

**Issue by Purg** [memex-explorer/image_space#158]
- [x] After pressing refine, we're put on a page other than one. I would expect that after hitting refine the user is brought back to page 1 (looking at ordered results 1-N).
- [x] Occasionally I will not be able to hit "Next" when the numbers at the bottom indicate that there should be a next page. For example, I was on a page 3 (showing 41-60) and the bottom indicated that there was a total of 1700 something images, but I couldn't hit next.
- [x] Maintaining the session is very fragile. I lose the session when I:
  - If I try to modify the URL to skip to another page
  - If I try to reload the page
  - Only occurs when having performed a similarity search or started one before selecting a session to load.

**Comment by chrismattmann** [comment]
I think this still happens wrt session fragility, but lack of cycles means we'll just have to deal with it for now
