### ISSUE TITLE
Feature: search using image url

### ISSUE THREAD

**Issue by khundman** [memex-explorer/image_space#159]
This would be really useful as it would enable users to directly submit an imagespace search by clicking an ad image in facetview (I'm working on facetview updates).

**Comment by jeffbaumes** [comment]
There should be a corresponding field in Solr that lists Solr image ids for the ad as opposed to the original image URL. Using these ids, it should be straightforward to construct a link back to ImageSpace that just works.

**Comment by khundman** [comment]
@jeffbaumes I see the connection now, thanks!

**Comment by wmburke** [comment]
So just to follow up - there IS a field in Solr currently that lists image IDs, right? This isn't something new that needs to be done. Am I following?

**Comment by khundman** [comment]
@wmburke Yep, the info is there. The "outpaths" field contains the paths (IDs) to each cached ad's content on the server, then you can use regex to see if the filepath has an image extension in it.

**Comment by wmburke** [comment]
Thanks, Kyle!
