### ISSUE TITLE
Uncaught TypeError thrown when using Flann metric 

### ISSUE THREAD

**Issue by harsham05** [memex-explorer/image_space#160]
@danlamanna @chrismattmann 
When using the Flann Image Similarity Metric, the below console error is thrown, which corresponds to 
https://github.com/memex-explorer/image_space/blob/master/imagespace/web_external/js/init.js#L204

```
init.js:204 Uncaught TypeError: Cannot read property 'split' of undefined
```

**Comment by chrismattmann** [comment]
got the same error, I have a PR to fix.

**Comment by harsham05** [comment]
@chrismattmann I had tried the Flann fix in Electronics ImageSpace deployment few weeks back, but there was another JS error. But seems like Flann is working now for Electronics ImageSpace

**Comment by chrismattmann** [comment]
yeah the error with Flann in Electronics was due to some issue with referencing the wrong opencv.so lib in site-packages which screwed up the tika and histogram extraction. Did you modify this at any point @harsham05 ?

**Comment by harsham05** [comment]
@chrismattmann Apologies for the late reply.
Nope, when deploying DHS Flann, I sourced the same "electronics" environment variables, to avoid building openCV from source again.
