### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by cosmoshsv** [memex-explorer/image_space#193]
On Ubuntu 16.04 64-bit Xenial Distribution, **pip install opencv numpy** was failing.
Both opencv and numpy got installed after running the following command :
**$ sudo pip install opencv-python**

Requesting to confirm if this would be compatible with image_space installation going further.

**Comment by chrismattmann** [comment]
@cosmoshsv how about a note indicating that if you get permissions warnings, you may need to enable sudo on (some or all of) the commands.

**Comment by cosmoshsv** [comment]
@chrismattmann - sorry for the confusion , the change was with the package name ( opencv-python ).

**Comment by chrismattmann** [comment]
Thanks
