### ISSUE TITLE
all the images' addressed to "localhost"

### ISSUE THREAD

**Issue by minkoonim** [memex-explorer/image_space#196]
I was following the quickstart using docker,
and got the search server working
the problem here is that if I connect remotely trying to use the image search service,
let's say if I find "flower" i get all the lists of the files which contains flower in the file name,
but images are not being displayed because they are address to "localhost:8989/images/***.jpg"
where can I change the setting for this?

imageUrl
http://localhost:8989/images/flower-260nw-67269706.jpg

**Comment by chrismattmann** [comment]
cannot reproduce this, closing.
