### ISSUE TITLE
Make ad/source of image easily findable

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/image_space#2]
We need to add this functionality to make the image searching useful in a broader context.

I've been thinking this, but we are also getting this feedback live from the User Surrogate Group right now.

**Comment by jeffbaumes** [comment]
Agreed. This means integrating with full IST data.

**Comment by wmburke** [comment]
I don't see where this would show up. I understand that you have said we will need to integrate to do this, but it should at least be obvious where this data would show up once it is live.

If this is difficult programmatically, just give me the info so I can clarify it when I send in the demo.

**Comment by jeffbaumes** [comment]
There is a mapping from image to ad somewhere, we would just need to find/create it.

In the demo I would place a link called "View ad" in the image detail panel.

I think this is relatively low-risk to get done by the QPR.

**Comment by jeffbaumes** [comment]
Our facetview/ad links support this pretty well now.
