### ISSUE TITLE
Image similarity uses

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/image_space#3]
Suggestion from USG: show a single graph from an uploaded photo (or from a single other photo that was selected).

Also, the interactive query tool will be REALLY useful here for identifying bad connections and fake photos (there are a lot of fake photos, identifying real photos is also useful -- although probably needs to be done by a human).

Would be great if this could also be used as a connection type between ads - in conjunction with identifying as fake or real.

**Comment by wmburke** [comment]
Some additional info on this (I was typing it while listening to a broader conversation with the USG).

First of all, a fake photo means that it's not an image of the actual girl referenced in the ad. 

Also, using this data as a connection type between ads really means making the information available for consumption in something like TellFinder as an additional data point. This may require a separate issue, but I at least wanted to capture the ideas here.

**Comment by jeffbaumes** [comment]
Closing for now - @wmburke if there is an updated formulation of this issue please file a new one.
