### ISSUE TITLE
A means by which to launch an image search from another app

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/image_space#4]
For example, if the end user could right click on an image in TellFinder and choose to search this image in ImageSpace. Is that easy? It may be something we want to work out at the QPR.

**Comment by jeffbaumes** [comment]
Yes, this should be fairly trivial to do through URL construction.

**Comment by jeffbaumes** [comment]
Since we have permalinks to everything this is about as easy as we can make it from our side.
