### ISSUE TITLE
Proxy Server Error on fetching image size distribution and Serial Number Disrtribution

### ISSUE THREAD

**Issue by nipurndoshi** [memex-explorer/image_space#40]
Steps to reproduct issue -
1) Click on reset search
2) Click on 'Image Size Distribution' link or 'Serial Number Distribution' link on the left.

Result : The modal keeps trying to load data. Nothing happens.
On checking further, Console shows this error for both the options -

---

502 Proxy Error <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>

<h1>Proxy Error</h1>

<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/imagespace/api/v1/imagepivot">GET&nbsp;/imagespace/api/v1/imagepivot</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>

**Comment by shivikathapar** [comment]
The above issue is faced in Chrome Version 43.0.2357.124 (64-bit).

**Comment by jeffbaumes** [comment]
Since these are not in the UI anymore, this is not something to fix.
