### ISSUE TITLE
Searching for images similar to uploaded image having SVG format not working

### ISSUE THREAD

**Issue by nipurndoshi** [memex-explorer/image_space#41]
Issue appears in : Broswer - Google Chrome, Version 43.0.2357.124 (64-bit)

Steps to reproduct issue -
1) Upload an SVG image.
2) Click on search icon at the bottom of uploaded image on the left

Result: The page keeps showing a loading icon and nothing appears.
Console shows the following error -

---

GET https://imagecat.memexproxy.com/imagespace/api/v1/imagesearch?url=https%3A%…3FSCiBFXzqzqHD0WSXQBYCRGQM06pi7vVCJwq6aLU3iQI31&histogram=%5B%5D&limit=100 500 (Internal Server Error)jQuery.ajaxTransport.send @ jquery.js:8623jQuery.extend.ajax @ jquery.js:8152Backbone.ajax @ backbone.js:1209_.extend.restRequest @ init.js:137imagespace.views.LayoutUserDataView.imagespace.View.extend.findSimilarImages @ UserDataView.js:130(anonymous function) @ UserDataView.js:101jQuery.Callbacks.fire @ jquery.js:3073jQuery.Callbacks.self.fireWith @ jquery.js:3185done @ jquery.js:8251jQuery.ajaxTransport.send.callback @ jquery.js:8598
init.js:120 500 Internal Server Error {"message": "ValueError: ValueError('No JSON object could be decoded',)", "trace": [["girder/api/rest.py", 279, "endpointDecorator", "val = fun(self, args, kwargs)"], ["girder/api/rest.py", 759, "GET", "return self.handleRoute('GET', path, params)"], ["girder/api/rest.py", 561, "handleRoute", "val = handler(*_kwargs)"], ["girder/api/access.py", 62, "accessDecorator", "return fun(_args, *_kwargs)"], ["/home/jbaumes/girder/plugins/imagespace/server/imagesearch_rest.py", 44, "getImageSearch", "'?url=' + params['url'] + '&num=' + str(limit), verify=False)"], ["/home/jbaumes/girder/env/lib/python2.7/site-packages/requests/models.py", 763, "json", "return json.loads(self.text, *_kwargs)"], ["/usr/lib64/python2.7/json/**init**.py", 338, "loads", "return _default_decoder.decode(s)"], ["/usr/lib64/python2.7/json/decoder.py", 365, "decode", "obj, end = self.raw_decode(s, idx=_w(s, 0).end())"], ["/usr/lib64/python2.7/json/decoder.py", 383, "raw_decode", "raise ValueError(\"No JSON object could be decoded\")"]], "type": "internal"}

---

**Comment by jeffbaumes** [comment]
We won't be able to do this with the limitations of at least the CMU similarity service.
