### ISSUE TITLE
Suggestion: Remove redundant attributes in search bar

### ISSUE THREAD

**Issue by nipurndoshi** [memex-explorer/image_space#43]
Issue appears in : Broswer - Google Chrome, Version 43.0.2357.124 (64-bit)

Steps to reproduce this : 
1) click on Reset Search
2) Click on 'i' of any image.
3) Click on '+' of an attribute to add to search.
4) Again Click on 'i' of the image and click on '+' of the same attribute.
Screenshot of the same is attached.

![screen shot 2015-06-12 at 1 16 02 pm](https://cloud.githubusercontent.com/assets/1675547/8139105/bd3c9fb4-1105-11e5-83ee-9eb9e38179b2.png)

**Comment by jeffbaumes** [comment]
Since we are string-appending, this would be a good amount of extra logic to parse the Solr queries, so I don't think we should tackle this.
