### ISSUE TITLE
Suggestion: Show notification when search is happening after clicking on '+' in Image Details

### ISSUE THREAD

**Issue by nipurndoshi** [memex-explorer/image_space#44]
Steps to reproduce this :
1) click on Reset Search
2) Click on 'i' of any image.
3) Click on '+' of an attribute to add to search.

Result : Resulting images are shown, but no notification is shown that a search is being carried out when adding a new attribute to the search.

**Comment by jeffbaumes** [comment]
There is now a notification on all searches.
