### ISSUE TITLE
Suggestion: Missing notification on Logout and app state not changed on Logout

### ISSUE THREAD

**Issue by shivikathapar** [memex-explorer/image_space#45]
Browser: Chrome
Version: Version 43.0.2357.124 (64-bit)

Not sure how important the log in feature is for pilot testing, but we might want to add a notification once a user has logged out saying "You have signed out". 

Also, once a user signs out, the app's state remains to the screen of last performed search. 
For example,

Steps:
1. I have a user account created with username : sthapar
2. I performed a search on an image from the database.
3. I logged out.

![screen shot 2015-06-12 at 1 24 14 pm](https://cloud.githubusercontent.com/assets/3753781/8139254/f56bbc52-1106-11e5-9f20-be83b2d1b4e1.png)

Result: After logging out, the screen still shows the last search results page. We could bring it back to the Home Page of ImageSpace.

**Comment by jeffbaumes** [comment]
I kind of like the "keeping the state" functionality on login/logout. Any other opinions? Either way I don't feel it's needed for this SUG/pilot.

**Comment by jeffbaumes** [comment]
Closing for now.
