### ISSUE TITLE
Adding "Source Query" to search bar from a saved image's attributes throws error

### ISSUE THREAD

**Issue by nipurndoshi** [memex-explorer/image_space#46]
Issue appears in : Broswer - Google Chrome, Version 43.0.2357.124 (64-bit)

Steps to reproduce this :
1) Click on Reset Search
2) Save any image by clicking on any image's save icon.
3) Scroll down to "Source Query" attribute which comes as the last attribute in the list.
4) Click on Search icon or plus icon on the right of Source Query attribute.

Result: Shows error on top right of the page.
Console shows - 

---

500 Internal Server Error {"message": "KeyError: KeyError('response',)", "trace": [["girder/api/rest.py", 279, "endpointDecorator", "val = fun(self, args, kwargs)"], ["girder/api/rest.py", 759, "GET", "return self.handleRoute('GET', path, params)"], ["girder/api/rest.py", 561, "handleRoute", "val = handler(*_kwargs)"], ["girder/api/access.py", 62, "accessDecorator", "return fun(_args, **kwargs)"], ["/home/jbaumes/girder/plugins/imagespace/server/imagesearch_rest.py", 53, "getImageSearch", "return result['response']['docs']"]], "type": "internal"}

---

**Comment by jeffbaumes** [comment]
Source query needs to be made visible again and made so you can't search/subsearch by it.
