### ISSUE TITLE
Notification for "search completed" on click of "Find Similar Images" missing

### ISSUE THREAD

**Issue by shivikathapar** [memex-explorer/image_space#47]
Browser: Chrome
Version: Version 43.0.2357.124 (64-bit)

Steps to reproduce the issue:
1. Cick on Reset Search
2. Save any image
3. On the left panel, click on "i" of the saved image.
4. Once the modal appears, click on "Find Similar Images".

Result: The modal disappears but there is no notification that the search was completed successfully or with error.

**Comment by chrismattmann** [comment]
Confirmed on http://imagecat.dyndns.org/imagespace/#search/*

**Comment by jeffbaumes** [comment]
Now you do receive feedback in this case that the search is running - then the images appear on completion. Closing this one.
