### ISSUE TITLE
Reverse "unblur" controls to "blur" controls

### ISSUE THREAD

**Issue by jeffbaumes** [memex-explorer/image_space#62]

**Comment by chrismattmann** [comment]
Hey Jeff what's this one about? Just more detail would be great

**Comment by jeffbaumes** [comment]
There is currently a control with options on when to unblur. We want these same options, but under a heading called "Blur" instead of "Unblur" to avoid confusion.

**Comment by jeffbaumes** [comment]
Another very easy one. Moving to SUG. @lawongsta also suggested that these controls could be removed altogether for certain domains. I would keep them but move them to a settings page (gear icon at the top). In the future I could see more settings being made available.
