### ISSUE TITLE
Possible issue with Docker install

### ISSUE THREAD

**Issue by lewismc** [memex-explorer/image_space#63]
Hi Folks,
Working on integration of [Georgetown's REST services](http://infosense.cs.georgetown.edu/dis/protocol.html) into image_space, I tried to recently build the docker image as

```
lmcgibbn@LMC-032857 /usr/local/image_space/imagespace(master) $ ./start-imagespace-docker.sh
```

this resulted in the below output

```
loads of steps...
...
Done, without errors.
 ---> bd9c6c0bfe75
Removing intermediate container 606df988bd6c
Step 24 : ENV KWDEMO_READY TRUE
 ---> Running in 3b5a070226ea
 ---> 8c73d76b8bf7
Removing intermediate container 3b5a070226ea
Step 25 : WORKDIR /home/kwuser/girder
 ---> Running in 953500bfd15e
 ---> 7de34aaaad43
Removing intermediate container 953500bfd15e
Step 26 : CMD sh -c python -m girder
 ---> Running in a18fcae6c882
 ---> fc2fbeb58515
Removing intermediate container a18fcae6c882
Successfully built fc2fbeb58515
/usr/bin/python: No module named cherrypy; 'girder' is a package and cannot be directly executed
```

The bottom message is concerning, I am not sure if this is OK or not.

**Comment by chrismattmann** [comment]
Girder needs to be git cloned and then Python run from the same level dir that girder is in

**Comment by lewismc** [comment]
Ack

On Saturday, July 25, 2015, Chris Mattmann notifications@github.com wrote:

> Girder needs to be git cloned and then Python run from the same level dir
> that girder is in
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/memex-explorer/image_space/issues/63#issuecomment-124883086
> .

## 

_Lewis_

**Comment by jeffbaumes** [comment]
I feel there are probably other issues here at this point - see #64. Closing this one for now.
