### ISSUE TITLE
Add Docker install to README

### ISSUE THREAD

**Issue by lewismc** [memex-explorer/image_space#64]
It is unclear that there is a docker container for image_space.
Would be great if we could make it explicit that there is one and then make it extremely easy for folks to find it and run it locally.
@jeffbaumes can you help me document this e.g. where is the docker container on DockerHub? Is it available for use?

**Comment by chrismattmann** [comment]
Thanks Lewis I don't use the docker Jeff built it for the laptop. I used intro understand how to install. It's fairly accurate.
I'll write up some install instructions.

**Comment by lewismc** [comment]
Hi Chris,
A docker install would be grand.
I also got image space up locally and install instructions are bang on.
I think a quick add to README would be great so I will do that.
This is based on the work were engaging in with Grace. It's going
reasonably well so demo time next week.

On Saturday, July 25, 2015, Chris Mattmann notifications@github.com wrote:

> Thanks Lewis I don't use the docker Jeff built it for the laptop. I used
> intro understand how to install. It's fairly accurate.
> I'll write up some install instructions.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/memex-explorer/image_space/issues/64#issuecomment-124882972
> .

## 

_Lewis_

**Comment by chrismattmann** [comment]
Great work my friend proud of you

**Comment by jeffbaumes** [comment]
@lewismc @chrismattmann great detective work getting somewhere with Docker. If either of you get stuck again let me know.

**Comment by jeffbaumes** [comment]
I don't know the state of this right now - so it's probably broken again. Once we have another use case for Docker installs we can get this working and documented again.

**Comment by danlamanna** [comment]
Closing this as a result of #172. Documentation lives [here](https://github.com/memex-explorer/image_space/tree/master/scripts/deploy).
