### ISSUE TITLE
Embed mode

### ISSUE THREAD

**Issue by jeffbaumes** [memex-explorer/image_space#75]

**Comment by rtapella** [comment]
Do we need to think through what this will look like a bit more? e.g. where the search bar goes?

**Comment by jeffbaumes** [comment]
Yeah. It's unclear what UI elements need to remain for this.

**Comment by jeffbaumes** [comment]
This is a good idea but not immediately needed for 2016 SUG. Removing the QPR milestone but I'll leave this task to implement later.

**Comment by chrismattmann** [comment]
won't fix
