### ISSUE TITLE
Image Graph Clustering

### ISSUE THREAD

**Issue by ghost** [memex-explorer/image_space#77]
Hi guys,

Did you ever seen this repo for building a Image Graph Neighborhood Viewer (it is using SIFT) ?
https://github.com/heathkh/iwct

eg: http://iwct-gallery.dasgizmo.net/data/tide_v12/results/html/imagegraph.html?initial_image=00000000000001657876

Cheers,
Luc Michalski

**Comment by jamestompkin** [comment]
Hi there - sorry for the long delay in replying.
With colleagues, I've looked at Image Webs and it's construction metaphor before.
From 2012 - http://people.mpi-inf.mpg.de/~kkim/mgc/MainPaper.pdf - see Section 3.2 for a discussion.

We don't have anything quite so featured, but our core graph building (link prediction) algorithm has code online in MATLAB too: http://gvv.mpi-inf.mpg.de/projects/CurvatureAwareRegularization/MatchGraphLinkPrediction.zip

Let me know if you're interested.
James

**Comment by chrismattmann** [comment]
very cool @jamestompkin @lucmichalski do you see this as something that could be made into a service we could call from e.g., Girder or Python?

**Comment by jamestompkin** [comment]
Disclamer: I don't know Girder, and my Python is 'speculative'.
However, the link prediction code isn't very long - 60 MATLAB lines in two functions? 
Easiest is probably just to reimplement it. It needs some linear algebra/solve functions, and currently uses MATLAB's sparse matrix support - how large a collection do you want to consider?

**Comment by chrismattmann** [comment]
thanks @jamestompkin  we are dealing with 10s of M of images.

**Comment by jamestompkin** [comment]
We're building a graph Laplacian with a sparse matrix, but 10M images sounds like a lot. ImageWebs still attempts to build a graph Laplacian, though, so that's not any better afaik. Let me talk to my colleague (the first author) and see what he thinks.

**Comment by chrismattmann** [comment]
cool @jamestompkin our core use case in a single domain is 40-50M images. we have many others which are 1-10M images. Smaller cases are ~100s of K of images.

**Comment by chrismattmann** [comment]
never finished
