### ISSUE TITLE
Make local installation easy

### ISSUE THREAD

**Issue by aashish24** [memex-explorer/image_space#79]
@lewismc and I were looking into testing image_space locally and ran into smaller issues (mostly missing reading the docs closely).

**Comment by aashish24** [comment]
- [x] Also, currently it requires images to exists locally for indexing purposes. For very large dataset that may not work. 
- [ ] Currently all of the env vars has to be set even though you may not use it
- [ ] We have quite a few steps to run manually before we can run the image_space

**Comment by harsham05** [comment]
Hi @aashish24 @lewismc I was able to get ImageSpace running locally just by leveraging the IMAGE_SPACE_SOLR REST endpoint env variable w/o indexing. I will send a PR updating the Readme. Thanks

**Comment by lewismc** [comment]
@harsham05 if you can update it would be appreciated as the docs currently indicate that you need
- the Solr core containing all of the images, and
- a local copy of all images. This is far from ideal as datasets will commonly grow to be larger than what may fit on one or two machines.

**Comment by aashish24** [comment]
@harsham05 this is great.. that will surely make things easy.  I can try your PR once you have it up.

**Comment by harsham05** [comment]
Hi @aashish24 , please let me know how it goes. Thanks

Fixed in https://github.com/memex-explorer/image_space/pull/80

**Comment by aashish24** [comment]
@harsham05 thanks

**Comment by harsham05** [comment]
@aashish24 you're welcome :)

```
IMAGE_SPACE_FLANN_INDEX need not be set for easy install
```

Also you can successfully deploy ImageSpace without setting the below env variables, you just wont be able to perform image_similarity queries by leveraging the below endpoints

```
IMAGE_SPACE_COLUMBIA_INDEX
IMAGE_SPACE_CMU_BACKGROUND_SEARCH
IMAGE_SPACE_GEORGETOWN_DOMAIN_DYNAMICS_SEARCH
```

**Comment by jeffbaumes** [comment]
@danlamanna has a PR coming in soon which improves docs and simplifies install.
