### ISSUE TITLE
Find Similar Images slow or worse

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/image_space#8]
I searched for 'girl' and opened the first image ("Sexy Schoolgirl Fetish", first metadata in the list is _version_: 1494086487025647600). When I click "Find similar images" it just processes - I left it for a couple of minutes to no avail.

**Comment by jeffbaumes** [comment]
My searches (including the one you mention) seem to return within 10 seconds. Is this repeatable from your side? I would also be sure to launch the app from incognito or cleaned-cache state to ensure you have the latest app.

**Comment by jeffbaumes** [comment]
@wmburke are you still seeing this or is it now working well for you?

**Comment by wmburke** [comment]
This does work fine now. Thanks, Jeff. As you said, it still takes about 10 seconds, but it works...
