### ISSUE TITLE
Separate Overview text into a “Help” and “About" page

### ISSUE THREAD

**Issue by lawongsta** [memex-explorer/image_space#81]
It is a lot of text for the user to see when they first enter the app. If it’s on separate tabs users don’t have to know “Return to these instructions at any time by clicking the Image Space text in the upper left.” They can simply click on the tab if they get lost. 

![is](https://cloud.githubusercontent.com/assets/12855060/11643375/5ff6f172-9cf8-11e5-98cc-5059ff74beb9.png)

The overview text could be split into two separate pages "Help" and "About. 
1. About Page:
   *Background
   *Goal
   *Partners
   *Learn More 
2. Help
   *Getting Started
   *How it works
   *Search Capabilities/ Image Matching/
   *Results of Image
   *Image Details/ Metadata 
   *Match
   *Attributes
   *System Attributes
   *Glossary of terms? (EXIF, OCR text)
   *Advanced
   *Search in Solr/Lucene

**Comment by jeffbaumes** [comment]
This is done.
