### ISSUE TITLE
Changing search box helper text to something intuitive for users

### ISSUE THREAD

**Issue by lawongsta** [memex-explorer/image_space#82]
<img width="640" alt="screen shot 2015-12-07 at 3 40 02 pm" src="https://cloud.githubusercontent.com/assets/12855060/11643457/d4e3c802-9cf8-11e5-92b2-04d610d1f4a2.png">

The helper text in the search box, “Search image text and attributes” may not be the most intuitive by end users who have pre-existing workflows for starting their searches. Something literal like, “Start by typing phone number, e-mail address, etc.” may be easier to understand.

**Comment by jeffbaumes** [comment]
This was changed to "Enter a search term or log in to drop an image..." which I think is much better than what it was.
