### ISSUE TITLE
Case building interface

### ISSUE THREAD

**Issue by lawongsta** [memex-explorer/image_space#84]
Thoughts/Questions regarding Weapons Landing Page:
-Could we replace the overview page with an organized grid of the images by categories? For example (similar images, geolocation, most searched, most frequent, abnormal, saved searches, specific keywords?)
-Can we show a listing of the most common keywords? Wordcloud or some sort of automated topic modelling thing?
-Link directly to popular gun ad websites
-How might we integrate weapon keywords in search?
-How can we show the user trends in images?
-How might we save bundles of images to specific projects/cases for investigators?

Grid Layout Options (8/14)
Linear results with a left hand side pane and no filtering
![search page with disclosure effect](https://cloud.githubusercontent.com/assets/12855060/11644681/0f72b1b8-9d03-11e5-9439-f3f11a37f8ce.png)

No left hand side pane, has filtering options. 
![search page with disclosure effect no lhs](https://cloud.githubusercontent.com/assets/12855060/11644704/343e1190-9d03-11e5-9404-cf3d0dc80ae4.png)

Left hand side page and has filtering
![-grid one-mode lhs filtering](https://cloud.githubusercontent.com/assets/12855060/11644565/f90e71c4-9d01-11e5-8fdf-df01452fe4b8.png)

No left hand side pane, but has filtering 
![-grid one-mode no lhs filtering](https://cloud.githubusercontent.com/assets/12855060/11644566/f90e8826-9d01-11e5-88c5-8663a5383aad.png)

**Comment by jeffbaumes** [comment]
I think we agree we should add case-building at some point, but this is currently out of scope for this SUG/pilot.

**Comment by chrismattmann** [comment]
incorporated into redesign and done
