### ISSUE TITLE
Missing features?

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/image_space#9]
I don't see how the following works in the current implementation:
1. Where camera serial numbers are provided in the EXIF metadata, search the open web for pictures from the same camera.
2. Search by image size - I see where you can limit the search or initiate a new search based on image height or width once you've already done one search, but I don't see where you can easily specify image dimensions for a search or where you can launch a new search based on image size.

**Comment by jeffbaumes** [comment]
The first point is a matter of instructing the user how to do this. We do not (and I can't see how we can) seamlessly integrate with an open web search by camera serial number in the short term. This appears to be mocked up in prior demos with a fixed set of stolen camera images. I will add instructions to the image detail window for images with exif tags.

For the second point, I am hoping to make image search by size better today.

**Comment by jeffbaumes** [comment]
Ok the first is addressed in the live version with a link out to a serial number search (an "image" icon appears if camera serial number is in the image attributes).

**Comment by jeffbaumes** [comment]
Search by image size is also now implemented, so I'm closing this issue.

**Comment by wmburke** [comment]
+1 awesome!
